pipeline:
  build:
    image: plugins/docker
    repo: kradalby/flexiday
    # auto_tag: true
    secrets: [ docker_username, docker_password ]
    tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    deployment: flexiday-deployment
    repo: kradalby/flexiday
    container: flexiday-container
    namespace: flexiday 
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    tag:
        - ${DRONE_COMMIT_SHA:0:8} 

  notify:
    image: drillster/drone-email
    host: smtp.fap.no
    skip_verify: true
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]
      
